// import type { Metadata } from "next";
// import { Toaster } from "@/components/ui/sonner"
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <Toaster />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from 'next';
import { Toaster } from "@/components/ui/sonner"
import './globals.css';

export const metadata: Metadata = {
  title: 'PS42 Luanda — Sistema de Gestão PlayStation',
  description: 'Plataforma oficial de gestão da PlayStation da 42 Luanda',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt" className="dark">
      <body className="min-h-screen bg-background antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  )
}